name: Migrate DDL

on: 
  pull_request:
    types:
      - closed   # trigger when PR is closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # choose your version

      # Install dependencies (if you have requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python

      # Run your Python script
      - name: Run script
        run: python main.py
