Create or replace table BYY.DBO.BYY_GLIDE_PATH
(
    PATH_ID               NUMBER(10)       NOT NULL,
    PATH_NAME             VARCHAR2(100)    NOT NULL,
    PATH_DESCRIPTION      VARCHAR2(255),
    CREATED_AT            TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT            TIMESTAMP        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PATH_ID)
);