Create or replace table BYY.DBO.BYY_GLIDE_PATH_3
(
    PATH_ID               NUMBER(10)       NOT NULL,
    PATH_NAME             VARCHAR2(100)    NOT NULL,
    PATH_DESCRIPTION      VARCHAR2(255),
    CREATED_AT            TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT            TIMESTAMP        DEFAULT CURRENT_TIMESTAMP 

);
